### ISSUE TITLE
No Line Search Implementation?

### ISSUE THREAD

**Issue by Haoxiang-Wang** [eddardd/WBTransport#1]
Hi, 

I notice there are several lines of code for line search in the function of Sinkhorn Barycenter:
https://github.com/eddardd/WBTransport/blob/main/msda/barycenters.py#L117-L119
it seems you didn't append the implementation of the naive_line_search in this codebase. Could you provide this implementation? Did you find alpha = 1 is optimal?

**Comment by eddardd** [comment]
Hello!

Sorry for the delayed response. Well, actually we run some experiments locally with line search, but they always chose \theta = 1. We did not include line search in our final code for that reason.

Best regards
