### ISSUE TITLE
Questions about the paper notations

### ISSUE THREAD

**Issue by vicmax** [eddardd/WBTransport#2]
Thank you for sharing your work here! I have some questions about several details of the paper:

The notation in Eq.(8) is quiet confusing.  Does $y_{s_k}$ for $k=1,...,N$ above Eq.(8) mean that we combine the labels of all the $n_k$ samples in a certain source domain $k$ as a label vector $y_{s_k} \in \mathbb{R}^{n_k}$, and concatenate all the label vector for different domains together. And in Eq.(8), what is the meanings of the subscripts $j$ and $i$?  In Eq(8), $s_k$ is on the superscript, but on the subscript in the notation above Eq.(8)? It's quiet confusing. Could you please provide more clarifications about this?

**Comment by eddardd** [comment]
Hello!

Yes, this equation is not quite clear. What we do is concatenate the labels of all source domains into y_b. For some concrete example, you can see the file "cvpr_experiments.py", where in line 181 we call np.concatenate(ys, axis=0). None that, here, ys is a list of ys_k, for each source domain k. I hope that clarifies a little bit the confusion.

Best regards.
