### ISSUE TITLE
question about eq10

### ISSUE THREAD

**Issue by Fay-why** [eddardd/WBTransport#3]
Hi, dear author, thanks for your great job. 

I have a big question about the following equation, since this step aims to calculate the source domain aggregation barycenter, why the coupling γ space is (μ_s, μ_t)? I think it should be  (μ_s, μ_b) ?

![image](https://user-images.githubusercontent.com/19245670/229440699-e1341491-1b84-4bbf-a2a2-3c0c62eec564.png)

![image](https://user-images.githubusercontent.com/19245670/229441781-d583fe72-c27c-417a-8ddf-93899030520e.png)

**Comment by eddardd** [comment]
Hi Helen,

Thank you for your question. Yes, this is actually a typo. It is a coupling between μ_s and μ_b.

**Comment by Fay-why** [comment]
ok~ Thanks for your reply!

And I also want to know if this kind of domain adaptation [source domain, target domain] should have same label space? Because I have seen the following equation in your paper. 

![image](https://user-images.githubusercontent.com/19245670/229444301-ef8cf9fd-fdde-4a28-b6f7-fc3e6c9f8323.png)

**Comment by eddardd** [comment]
This is the covariate shift assumption. This is a necessary condition for doing unsupervised domain adaptation (i.e. without target labels). Under this assumption the distributional shift problem can be solved by applying a transformation to the features, while keeping labels unchanged.

**Comment by Fay-why** [comment]
Thanks! I will close this issue.
